"""Distribution + agent-signalling protocol for the Conductor.

Owns the staging directory layout, prompt injection (including the COMMIT PROTOCOL
additions and the ``module_key`` stamp), the ``launch_agents.sh`` generator that opens
one Terminal window per agent, and the ``.done`` / ``.conflict_report.txt`` filesystem
handshake the agents use to signal completion and receive conflict reports.
"""

from __future__ import annotations

import json
import subprocess
import time
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path

    from conductor.session import AgentSpec, ConductorSession

DONE_FLAG = ".done"
CONFLICT_REPORT_FILE = ".conflict_report.txt"
SCHEMA_TEMPLATE = ".cdmad/session_schema.json"
LAUNCH_SCRIPT = "launch_agents.sh"
PROMPT_FILE = "PROMPT.md"


def _log(message: str) -> None:
    print(message)

_COMMIT_PROTOCOL = """\

--- COMMIT PROTOCOL (Conductor-managed) ---
WRITE ONLY to your staging directory:
  {staging_dir}
Every file you produce MUST live under that exact path. Do NOT write, edit, or
create files anywhere else in the target repository, and do NOT run git yourself.
The Conductor copies your staging dir into the repo atomically after proofing —
files written directly to the repo are NOT collected, will NOT be committed, and
break the gate chain. Staging is the only path your output reaches the repo.

When your files are complete, signal the Conductor:
  touch {staging_dir}/.done

Before resubmitting after a conflict, read carefully:
  {staging_dir}/.conflict_report.txt
Address EVERY point in the report before rewriting.
Do not resubmit until all points are resolved.
"""


def staging_dir(session: ConductorSession, agent: AgentSpec) -> Path:
    return agent.staging_dir(session.staging_root)


def distribute(session: ConductorSession) -> None:
    """Create each agent's staging directory and write its prompt + schema template."""
    for agent in session.agents:
        adir = staging_dir(session, agent)
        adir.mkdir(parents=True, exist_ok=True)
        _write_prompt(adir, agent)
        _write_schema_template(adir, session, agent)


def _write_prompt(adir: Path, agent: AgentSpec) -> None:
    body = agent.prompt + _COMMIT_PROTOCOL.format(staging_dir=adir)
    (adir / PROMPT_FILE).write_text(body)


def _write_schema_template(adir: Path, session: ConductorSession, agent: AgentSpec) -> None:
    """Stamp the agent's session_schema.json with module_key + identifiers.

    The agent fills in modules/exposes/consumes; the Conductor owns module_key so
    the gate's VDB lookups resolve regardless of directory naming.
    """
    empty_module: dict[str, list[Any]] = {
        "contracts": [],
        "exposes": [],
        "consumes": [],
        "assumptions": [],
        "dependencies": [],
    }
    template = {
        "module_key": agent.module_key,
        "repo": session.repo_name,
        "session_id": session.session_id,
        "modules": {agent.module_key: empty_module},
    }
    schema_path = adir / SCHEMA_TEMPLATE
    schema_path.parent.mkdir(parents=True, exist_ok=True)
    schema_path.write_text(json.dumps(template, indent=2))


# ── Launch script ────────────────────────────────────────────────

# Header is raw so the backslash-escapes survive verbatim into the file. The heredoc
# is intentionally unquoted: ``$1`` expands to the staging dir at launch time, while
# the ``\"`` around the echo message are escaped so they reach osascript untouched.
# claude runs interactively (no -p) — that path needs no API key and works with Max.
# pbcopy targets the single global macOS pasteboard, so the windows MUST be opened one
# at a time: write_launch_script emits a ``read`` pause after each launch so the operator
# pastes (⌘V) into that window before the next pbcopy overwrites the clipboard. Opening
# every window at once lets the last pbcopy win and every agent gets the last agent's
# prompt (the Phase 4 "every agent got Agent 6's prompt" failure).
# The osascript do-script line, fragmented across source lines to stay under the line
# limit; implicit concatenation yields one physical line in the generated script. The
# literal quotes wrap the AppleScript string; the inner \" are escaped for osascript.
_DO_SCRIPT_LINE = (
    r'''    do script "cd '$1' && cat PROMPT.md | pbcopy && '''
    r'''echo \"Prompt copied to clipboard — paste with ⌘V\" && '''
    r'''claude --dangerously-skip-permissions"'''
)

_LAUNCH_HEADER = "\n".join([
    "#!/usr/bin/env bash",
    "# Auto-generated by the Conductor — launches one Terminal window per agent.",
    "# Each window cd's into the agent's staging dir, copies PROMPT.md to the clipboard,",
    "# then launches claude interactively for the operator to paste into.",
    "# Windows open ONE AT A TIME: the script pauses for you to paste (⌘V) into each",
    "# window before opening the next, because pbcopy uses the single global clipboard",
    "# and launching them all at once leaves the last agent's prompt on every window.",
    "# Regenerated on every distribute; do not edit by hand.",
    "set -euo pipefail",
    "",
    "launch() {",
    "    osascript <<OSA",
    'tell application "Terminal"',
    "    activate",
    _DO_SCRIPT_LINE,
    "end tell",
    "OSA",
    "}",
    "",
    "",
])


def write_launch_script(session: ConductorSession) -> Path:
    """Write launch_agents.sh under the staging root and return its path.

    The script opens one Terminal window per agent (via osascript), each cd'ing into
    that agent's staging dir, copying the already-written PROMPT.md to the clipboard,
    and launching claude interactively for the operator to paste the prompt into.

    Windows are launched serially with a ``read`` pause between them: pbcopy writes to
    the single global macOS pasteboard, so the operator must paste into each window
    before the next window's pbcopy overwrites the clipboard. Opening every window at
    once would leave the last agent's prompt on the clipboard for all of them — the
    Phase 4 failure where every agent received Agent 6's prompt.
    """
    agents = session.agents
    total = len(agents)
    lines: list[str] = []
    for i, agent in enumerate(agents, start=1):
        lines.append(f"launch '{staging_dir(session, agent)}'")
        tail = (
            "then press Enter to launch the next agent... "
            if i < total
            else "then press Enter to finish. "
        )
        prompt = f"Agent {i}/{total} launched — paste the prompt into its window with ⌘V, {tail}"
        lines.append(f'read -r -p "{prompt}"')
    body = _LAUNCH_HEADER + "\n".join(lines) + "\n"
    script_path = session.staging_root / LAUNCH_SCRIPT
    session.staging_root.mkdir(parents=True, exist_ok=True)
    script_path.write_text(body)
    script_path.chmod(0o755)
    return script_path


# ── Agent signalling ─────────────────────────────────────────────


def is_done(session: ConductorSession, agent: AgentSpec) -> bool:
    return (staging_dir(session, agent) / DONE_FLAG).exists()


def clear_done(session: ConductorSession, agent: AgentSpec) -> None:
    flag = staging_dir(session, agent) / DONE_FLAG
    if flag.exists():
        flag.unlink()


def write_conflict_report(session: ConductorSession, agent: AgentSpec, report: str) -> None:
    """Write the conflict report and clear .done so the agent re-signals when fixed."""
    adir = staging_dir(session, agent)
    (adir / CONFLICT_REPORT_FILE).write_text(report)
    clear_done(session, agent)


def read_agent_schema(session: ConductorSession, agent: AgentSpec) -> dict[str, Any]:
    """Read the agent's produced session_schema.json (empty dict if absent/invalid)."""
    schema_path = staging_dir(session, agent) / SCHEMA_TEMPLATE
    if not schema_path.exists():
        return {}
    try:
        data = json.loads(schema_path.read_text())
    except (json.JSONDecodeError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def collect_files(session: ConductorSession, agent: AgentSpec) -> list[str]:
    """Repo-relative file paths the agent produced under its staging root."""
    adir = staging_dir(session, agent)
    out: list[str] = []
    for path in sorted(adir.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(adir)
        if rel.name in {DONE_FLAG, CONFLICT_REPORT_FILE, PROMPT_FILE}:
            continue
        if rel.parts and rel.parts[0] == ".cdmad":
            continue
        out.append(str(rel))
    return out


def staging_is_empty(session: ConductorSession, agent: AgentSpec) -> bool:
    """True if the agent has produced no deliverable files in its staging dir."""
    return not collect_files(session, agent)


def repo_untracked_for_agent(session: ConductorSession, agent: AgentSpec) -> list[str]:
    """Untracked repo files whose path matches the agent's module_key.

    Soft-signal heuristic: when an agent ignores the staging-only protocol and writes
    deliverables straight into the target repo, its staging dir stays empty but new
    untracked files matching its module_key appear. Matching is by module_key tokens
    (split on ``_``, dropping tokens shorter than 3 chars) — every token must appear
    in the lowercased path, so ``memory_allocator`` matches ``src/memory/allocator.py``.
    Returns [] on any git error; this is advisory only, never authoritative.
    """
    tokens = [t for t in agent.module_key.lower().split("_") if len(t) >= 3]
    if not tokens:
        return []
    try:
        result = subprocess.run(
            ["git", "-C", str(session.repo_root), "status",
             "--porcelain", "--untracked-files=all"],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return []
    if result.returncode != 0:
        return []
    matches: list[str] = []
    for line in result.stdout.splitlines():
        if not line.startswith("??"):
            continue
        path = line[3:].strip()
        lowered = path.lower()
        if all(tok in lowered for tok in tokens):
            matches.append(path)
    return matches


def wait_for_done(
    session: ConductorSession,
    agents: list[AgentSpec],
    poll_interval: float = 1.0,
    timeout: float | None = None,
) -> bool:
    """Block until all given agents have signalled. Returns True if all signalled.

    An agent signals normally by writing ``.done``. As a fallback, an agent whose
    staging dir is empty but whose module_key matches new untracked files in the repo
    is treated as a *soft signal*: it wrote to the repo instead of staging (violating
    the protocol), so we warn once and stop waiting on it rather than blocking forever.
    ``atomic_commit`` will then surface the empty staging and refuse the commit.
    """
    deadline = None if timeout is None else time.monotonic() + timeout
    pending = list(agents)
    warned: set[str] = set()
    while pending:
        still_pending: list[AgentSpec] = []
        for a in pending:
            if is_done(session, a):
                continue
            if staging_is_empty(session, a):
                stray = repo_untracked_for_agent(session, a)
                if stray:
                    if a.agent_id not in warned:
                        warned.add(a.agent_id)
                        _log(
                            f"CONDUCTOR  ⚠ {a.agent_id} ({a.module_key}) staged nothing "
                            f"but wrote {len(stray)} matching file(s) directly to the repo "
                            f"(e.g. {stray[0]}) — treating as soft signal, not waiting. "
                            "Agents MUST write to staging only.",
                        )
                    continue
            still_pending.append(a)
        pending = still_pending
        if not pending:
            return True
        if deadline is not None and time.monotonic() >= deadline:
            return False
        time.sleep(poll_interval)
    return True
